id: PCAC9DCAA
initial_creation_type: ocr
source_metadata:
  volumes:
    a020d365d54a4499a7b41021d5ed754a:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: ལེའུ་བཅོ་བརྒྱད་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1453
      volume_number: 15
